# Generated by Django 4.1.2 on 2022-11-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='averageStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='minimumStock',
            field=models.IntegerField(default=0),
        ),
    ]
