# Generated by Django 4.1.2 on 2022-11-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_averagestock_product_minimumstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateExpiration', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('product', models.ManyToManyField(blank=True, to='products.product')),
            ],
            options={
                'verbose_name': 'Expiration',
                'verbose_name_plural': 'Expirations',
                'db_table': 'expiration',
                'abstract': False,
            },
        ),
    ]
