# Generated by Django 4.1.2 on 2022-11-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hasExpiration',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='expiration',
            name='product',
        ),
        migrations.AddField(
            model_name='expiration',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
