# Generated by Django 4.1.2 on 2022-11-04 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KardexHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movementType', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('totalPrice', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucherType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.vouchertype')),
            ],
            options={
                'verbose_name': 'KardexHeader',
                'verbose_name_plural': 'Kardex Headers',
                'db_table': 'kardexheader',
                'abstract': False,
            },
        ),
    ]
