# Generated by Django 4.1.2 on 2022-11-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('kardex', '0002_kardexheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='KardexDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('idKardexHeader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_header', to='kardex.kardexheader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'KardexDetail',
                'verbose_name_plural': 'Kardex Details',
                'db_table': 'kardexdetail',
                'abstract': False,
            },
        ),
    ]
