# Generated by Django 4.1.2 on 2022-11-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0004_alter_kardexdetail_idkardexheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexdetail',
            name='idKardexHeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detail', to='kardex.kardexheader'),
        ),
    ]
