# Generated by Django 4.1.2 on 2022-11-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0005_alter_kardexdetail_idkardexheader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardexdetail',
            old_name='idKardexHeader',
            new_name='kardexHeader',
        ),
    ]
