# Generated by Django 4.1.2 on 2022-11-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0006_rename_idkardexheader_kardexdetail_kardexheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexdetail',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
